# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    env_file:
      - .env.mongo_auth

  backend:
    container_name: backend
    image: node:latest
    depends_on:
     - mongo
    restart: always
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - .env.mongo_auth
    command: npm ci && npm start
